#!/usr/bin/python
from marionette_driver.marionette import Marionette

client = Marionette()
client.start_session()

# from https://h3manth.com/content/javascript-one-liner-extracting-unique-words-webpages
js = "return document.body.textContent.split(/\s+/).sort().filter( function(v,i,o){return v!==o[i-1];});"

words=client.execute_script(js)
for word in sorted(words):
    print word
